.TH eos 7 2010-oct "linux" "heatherly custom tools manual"

.SH NAME
.B eos
\- simple, reliable, and transparent system initialization

.SH PATRON
.B eos-rhododactylos
(rosy-fingered dawn) titaness of daybreak

.SH IMAGERY
radiant worman with white wings, golden arms, and rosy fingers

.SH SUMMARY
eos is a standardized batch-processing control program which generalizes and
removes complexity from invidual scripts/programs.  eos specifically drives
system start-up, shut-down, and cleanup as well.

.SH DOCUMENTATION FILES
.nf
eos (1)            command-line usage 
.nf
eos (5)            configuration and data files
.nf
eos (7)      [***] decision rationale, objectives, and overview
